# Book settings
title: Cuántica I
author: M. en C. Juan Felipe Huan Lew Yee, Dr. José Eduardo Barrios Vargas, Dr. Jorge Martín del Campo Ramírez. Departamento de Física y Química Teórica, Facultad de Química, Universidad Nacional Autónoma de México
html:
  extra_footer : |
      <div>
      <img src="https://github.com/felipelewyee/Cuantica-I/blob/master/logo_unam.png?raw=true" alt="logo_UNAM", style="width: 5%">
      <img src="https://github.com/felipelewyee/Cuantica-I/blob/master/logoFacultadQuimica.jpg?raw=true" alt="logo_FQ", style="width: 5%">
          <br>© D.R. UNIVERSIDAD NACIONAL AUTÓNOMA DE MÉXICO 2022<br>Universidad Nacional Autónoma de México<br>Facultad de Química<br>Prohibida la reproducción total o parcial por cualquier medio, sin la autorización escrita del titular de los derechos patrimoniales.<br>Hecho en México<br>Publicación aprobada por el Comité Editorial de la Facultad de Química.
      </div>
logo: logo.png

sphinx:
  config:
    html_show_copyright: false

launch_buttons:
  colab_url                 : https://colab.research.google.com # The URL of Google Colab (e.g., https://colab.research.google.com)
  binderhub_url             : https://mybinder.org
  thebe                     : true

repository:
  url                       : https://github.com/felipelewyee/Cuantica-I  # The URL to your book's repository
  branch                    : master  # Which branch of the repository should be used when creating links

latex:
  latex_documents:
    targetname: book.tex

execute:
  timeout: 100

parse:
  myst_enable_extensions:
    - "amsmath"
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_admonition"
    - "html_image"
    - "linkify"
    - "replacements"
    - "smartquotes"
    - "substitution"
